apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: sample-app
    mytag: revision-1
  name: sample-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      deploymentconfig: sample-app
  template:
    metadata:
      labels:
        app: sample-app
        deploymentconfig: sample-app
      name: sample-app
    spec:
      containers:
      - name: apache
        image: registry.access.redhat.com/ubi8/httpd-24:1-226
        #imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: sample-app-configmap
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: sample-app-configmap
        configMap:
          defaultMode: 438
          name: sample-app-configmap
