apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-configmap
  labels:
    app.kubernetes.io/instance: sample-app
data:
  "index.html": |-
    <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>This is simple sample application running on another repo</title>
        </head>
          <body>
            <h1>Sample application</h1>
            <br/>
            <h2>
            Hub Cluster domain is '{{ .Values.global.hubClusterDomain }}' <br>
            Pod is running on Local Cluster Domain '{{ .Values.global.localClusterDomain }}' <br>
            </h2>
          </body>
      </html>
